config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/home' => "pages#home"
  get '/about' => "pages#about"
  get '/menu' => "pages#menu"
  get '/contact' => "pages#contact"

  # resources :orders, except: [:show] do
  #   # these are the "add item to order" and "remove item from order" routes
  #   resources :items, only: [:create, :destroy]
  # end

  resources :orders do
    # these are the "add item to order" and "remove item from order" routes
    resources :items, only: [:create, :destroy]
  end

  post '/orders/:id/edit' => "orders#edit"

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :orders

  def self.categories
    self.all.pluck(:category).uniq
  end

  def self.appetizers
    self.where(category: "Appetizers")
  end

  def self.salads
    self.where(category: "Salads")
  end

  def self.soups
    self.where(category: "Soups")
  end

  def self.noodles
    self.where(category: "Noodles")
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

    helper_method :current_user

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'You must be logged in!' if current_user.nil?
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    # get the order and item from the form
    current_item = Item.find params[:item][:id]
    order = Order.find params[:order_id]

    # add the item to the order
    order.items << current_item

    # go back!
    redirect_to edit_order_path(order)
  end

  def destroy
    order = Order.find params[:order_id]
    item = Item.find params[:id]
    order.items.delete(item)
    redirect_to edit_order_path(order)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authorize, only: [:show, :edit, :create, :index]


  def index
    @orders = current_user.orders
    @new_order = Order.new
  end


  def show
    @order = Order.find(params[:id])
  end


  def new
    @order = Order.new
  end


  def create
    @order      = Order.new(params.require(:order).permit(:name))
    @order.user = current_user

    if @order.save
      redirect_to edit_order_path(@order)
    else
      render :new
    end
  end

  def edit
    @order = Order.find(params[:id])
    @item  = Item.new
  end


  def update
  @order = Order.find(params[:id])

    if @order.update_attributes(params.require(:order).permit(:name, :total, :user))
      redirect_to orders_path
    else
      render :edit
    end
  end


  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  def total
    @order = Order.find(params[:id].Item.sum(:cost))
  end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def about
  end

  def menu
    @items = Item.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up"
      redirect_to root_path
    else
      render :new
    end
  end


private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mint Thai</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>

<body>

<p id="nav_bar">
  <ul class="nav nav-pills">
    <li role="presentation"><a href="/home">H o m e</a></li>
    <li role="presentation"><a href="/about">A b o u t &nbsp;&nbsp; U s</a></li>
    <li role="presentation"><a href="/menu">M e n u</a></li>
    <li role="presentation"><a href="/orders">O r d e r</a></li>
    <li role="presentation"><a href="/contact">C o n t a c t &nbsp;&nbsp; U s</a></li>
    <li role="presentation" class="nav nav-pills pull-right">
      <% if current_user %>
        <li role="presentation" class="nav nav-pills pull-right"><%= link_to 'L o g o u t', session_path('dummy'), method: :delete %></li>
        <li role="presentation" class="nav nav-pills pull-right"><%= link_to current_user.first_name, orders_path %></li>
      <% else %>
        <%= link_to 'L o g i n', login_path %>
        <li role="presentation" class="nav nav-pills pull-right"><%= link_to 'S i g n  U p', new_user_path %></li>
      <% end %>
    </li>
  </ul>
</p>

<%= yield %>

</body>
</html>

app/views/orders/edit.html.erb
<body id="orders_page">

<!-- EDIT ORDER : SHOWS NAME OF THE ORDER -->
    <div>
      <h2 style="color: white">Edit your order</h2>
        <%= form_for @order do |f| %>
          <div style="color:white"><%= f.label :name %><br></div>
          <%= f.text_field :name %>
          <%= f.submit "Change Name" %>
        <% end %>
    </div>

  <div id="orders"

<!-- CALCULATES AND SHOWS THE ITEM SANS TAX -->


    <% order_subtotal = 0.0 %>
    <div id="current_orders" class="edit_orders">
      <h3 style="color: black">Current Items</h3>
        <% @order.items.each do |item| %>
          <% order_subtotal += item.cost %>
          <div class="row">
            <div class="col-sm-9">
              <div class="row">
                <div class="col-xs-8 col-sm-6 text-left">
                  <%= item.name %>
                </div>
                <div class="col-xs-4 col-sm-6 text-right">
                  <%= number_to_currency(item.cost)%> &nbsp;&nbsp;
                  <%= link_to '<i class="glyphicon glyphicon-remove" style="color: red;"></i>'.html_safe, order_item_path(@order, item), method: :delete %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <hr>
        <% tax = (order_subtotal * 0.09).round(2) %>
          <ul class="text-right" style="list-style: none">
            <li>Subtotal: <%= number_to_currency(order_subtotal) %></li>
            <li>Tax: <%= number_to_currency(tax) %></li>
          </ul>
      <h4>Total: <%= number_to_currency(order_subtotal + tax) %></h4>
    </div>

    <div class="divider"></div>

<!-- ADDING ITEMS -->

    <div id="adding_items" class="edit_orders">

        <h3 style="color: black">Add Appetizers</h3>
        <%= form_for [@order, @item] do |f| %>
          <%= f.collection_select :id, Item.appetizers, :id, :name %>
          <%= f.submit "Add!" %>
        <% end %>

        <h3 style="color: black">Add Salads</h3>
        <%= form_for [@order, @item] do |f| %>
          <%= f.collection_select :id, Item.salads, :id, :name %>
          <%= f.submit "Add!" %>
        <% end %>

        <h3 style="color: black">Add Soups</h3>
        <%= form_for [@order, @item] do |f| %>
          <%= f.collection_select :id, Item.soups, :id, :name %>
          <%= f.submit "Add!" %>
        <% end %>

         <h3 style="color: black">Add Noodles</h3>
        <%= form_for [@order, @item] do |f| %>
          <%= f.collection_select :id, Item.noodles, :id, :name %>
          <%= f.submit "Add!" %>
        <% end %>

        <br>

        <button><%= link_to "Submit Order", orders_path, data: { confirm: "Thank you for submitting your order"} %></button>
        <button><%= link_to "Cancel Order", orders_path %></button>

    </div>

  </div>

</body>

app/views/orders/index.html.erb
<body id="orders_page">

  <div id="orders">
      <h2>Welcome, how may we serve you?</h2>

      <br>

      <h4>Create a New Order</h4>
      <%= form_for @new_order do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
        <%= f.submit "New Order" %>
      <% end %>
      </ul>

      <br><br>

      <h4>Past Orders:</h4>
      <ul>
        <% @orders.each do |order| %>
          <div>
            <%= order.name %>&nbsp;
            <%= link_to '<i class="glyphicon glyphicon-eye-open" style="color: black;"></i>'.html_safe, order_path(order.id) %> &nbsp;
            <%= link_to '<i class="glyphicon glyphicon-pencil" style="color: black;"></i>'.html_safe, edit_order_path(order.id),
                method: :edit %> &nbsp;
            <%= link_to '<i class="glyphicon glyphicon-remove" style="color: red;"></i>'.html_safe, order_path(order.id),
                method: :delete,
                data: { confirm: "Are you sure you want to delete this order?"} %>
          </div>
        <% end %>
      </ul>
  </div>
</body>

app/views/orders/show.html.erb
<body id="show_page">

  <div id="show">

    <h1> <%= @order.name %> </h1>

    <% order_subtotal = 0.0 %>
      <div>
        <h3 style="color: black">Order Items</h3>
          <% @order.items.each do |item| %>
              <% order_subtotal += item.cost %>
              <div class="row">
                <div class="col-sm-9">
                  <div class="row">
                    <div class="col-xs-8 col-sm-6 text-left" id="show_name">
                      <%= item.name %>
                    </div>
                    <div class="col-xs-4 col-sm-6 text-right" id="show_price">
                      <%= number_to_currency(item.cost)%>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
        <div style="color: black"><hr></div>
          <% tax = (order_subtotal * 0.09).round(2) %>
            <ul class="text-right" style="list-style: none">
              <li>Subtotal: <%= number_to_currency(order_subtotal) %></li>
              <li>Tax: <%= number_to_currency(tax) %></li>
            </ul>
        <h4>Total: <%= number_to_currency(order_subtotal + tax) %></h4>
      </div>
  </div>

  <%= link_to "Back to the list!", orders_path %>

</body>

app/views/pages/about.html.erb
<body id="about_page">

  <div id="about">

    <h1>A B O U T&nbsp;&nbsp;&nbsp;U S</h1>
    <br>
    <div>
      <img class="pictures" src = "/krapow.jpg">
      <img class="pictures" src = "/mango.jpg">
      <img class="pictures" src = "/soup.jpg">
    </div>
    <br>
    <p class="so">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

  <br>
  <br>
  <br>

</body>

app/views/pages/contact.html.erb
 <body id="contact_page">

  <div class="contact">

    <div id="map">
      <img src ='https://i.imgur.com/Tbv9OIq.png'>
    </div>


    <div id="info">
      <h3>Address</h3>
        <p>12345 Memorial Parkway</p>
        <p>Houston, TX 71839</p>
      <h3>Hours of Operation</h3>
        <p>Monday - Thursday: 10am - 11pm</p>
        <p>Friday & Saturday: 10am - 12am</p>
        <p>Sunday: 12pm - 9pm</p>
      <h3>Phone Number</h3>
        <p>832.147.6857</p>

    </div>


  </div>
</body>

app/views/pages/home.html.erb
<body id="home_page">

  <div id="home">

    <h1 style="text-decoration: underline" id="mint">M I N T<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; T H A I</h1>

  </div>

</body>

app/views/pages/menu.html.erb
<body id="menu_page">

  <div id="menu">

    <h1 class="food_text">a p p e t i z e r s</h1>
    <% Item.appetizers.each do |item| %>
    <br>
      <article>
          <h4><strong class="food_text"><p><%= item.name %></p></strong></h4>
          <p class="food_text"><%= item.amount %></p>
          <p class="food_text"><%= item.description %></p>
          <p class="food_text"><%= item.cost %></p>
      </article>
    <% end %>

    <br><br><br>

    <h1 class="food_text">s a l a d s</h1>
    <% Item.salads.each do |item| %>
      <br>
      <article>
          <h4><strong class="food_text"><p><%= item.name %></p></strong></h4>
          <p class="food_text"><%= item.amount %></p>
          <p class="food_text"><%= item.description %></p>
          <p class="food_text"><%= item.cost %></p>
      </article>
    <% end %>

    <br><br><br>

    <h1 class="food_text">s o u p s</h1>
    <% Item.soups.each do |item| %>
      <br>
      <article>
          <h4><strong class="food_text"><p><%= item.name %></p></strong></h4>
          <p class="food_text"><%= item.amount %></p>
          <p class="food_text"><%= item.description %></p>
          <p class="food_text"><%= item.cost %></p>
      </article>
    <% end %>

    <br><br><br>

    <h1 class="food_text">n o o d l e s</h1>
    <% Item.noodles.each do |item| %>
      <br>
      <article>
          <h4><strong class="food_text"><p><%= item.name %></p></strong></h4>
          <p class="food_text"><%= item.amount %></p>
          <p class="food_text"><%= item.description %></p>
          <p class="food_text"><%= item.cost %></p>
      </article>
    <% end %>

  </div>

</body>

  <!--
    <%# Item.categories.each do |category| %>
      <h2 id="menu_title"><%#= category.downcase.split("").join(" ") %></h2>
      <%# Item.where(category: category).each do |item| %>
        <br>
        <article>
            <h4><strong class="food_text" id="food_name"><p><%#= item.name %></p></strong></h4>
            <p class="food_text"><%#= item.amount %></p>
            <p class="food_text"><%#= item.description %></p>
            <p class="food_text"><%#= item.cost %></p>
        </article>
      <%# end %>
      <hr>
    <%# end %>
  -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="sign_up">
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <br>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>